maps:
  woods:
    name: "&cWoods"
    rep_item: "dark_oak_log"
    folder: "WOODS 1.01 BY lockshane"
kits:
  fighter:
    name: "&6Fighter"
    rep_item: "iron_sword"
    items:
      iron_sword:
        unbreakable: yes
      iron_axe:
        unbreakable: yes
    armor:
      leather_helmet:
        unbreakable: yes
      leather_chestplate:
        unbreakable: yes
      leather_leggings:
        unbreakable: yes
      leather_boots:
        unbreakable: yes
    off_hand:
      shield:
        unbreakable: no