name: SimpleGenerators
version: 1.1
api-version: 1.16
main: plainplaying.plugin.gens.SimpleGenerators
commands:
  sell:
    description: Sell all items in the player's inventory, priced using the config
    aliases: [s,sellall]
  SimpleGenerators:
    description: General plugin information and commands
    aliases: [sg,simplegens,simplegenerators,sgens]
depend:
  - Vault
permissions:
  simplegenerators.admin.reload:
    description: Allows a player to reload the plugin
  simplegenerators.gen.add:
    description: Allows a player to add a generator
  simplegenerators.gen.remove:
    description: Allows a player to remove a generator
  simplegenerators.gen.edit:
    description: Allows a player to edit a generator
  simplegenerators.gen.get:
    description: Allows a player to give themselves a generator
  simplegenerators.item.add:
    description: Allows a player to add an item
  simplegenerators.item.remove:
    description: Allows a player to remove an item
  simplegenerators.item.edit:
    description: Allows a player to edit an item
  simplegenerators.sellwand.add:
    description: Allows a player to add a sellwand
  simplegenerators.sellwand.remove:
    description: Allows a player to remove a sellwand
  simplegenerators.sellwand.edit:
    description: Allows a player to edit a sellwand


